### ISSUE TITLE
Provide an example

### ISSUE THREAD

**Issue by akuji1993** [MichaelRFox/foxToolTip.js#1]
Hey, 

your idea is very very appreciated and I will try to work with your library since d3-tip seems to be deprecated with d3_v4-alpha. But please provide some examples. It makes it a lot easier to get right into your work. Other than that, looks great! Thanks for helping the D3 community. 

Greetings.

**Comment by MichaelRFox** [comment]
Take a look at the index.html for some examples.  Working on a d3 specific example.  Should be up in a day or two.

regards

m fox

**Comment by akuji1993** [comment]
Example looks good, thanks 

Greetings.
